src/app/[category]/page.tsx
=> fix: fixed markdown rendering

src/modules/Toolbar/Toolbar.tsx, src/modules/Toolbar/components/Filter/Filter.tsx, src/modules/Toolbar/components/FilterForm/FilterForm.tsx, src/modules/Toolbar/components/SortBy/SortBy.tsx
- now filters are applying dynamically
- sort selector are preserving state with query string
=> feat: updated toolbar to dynamic filtering

src/modules/Toolbar/Toolbar.tsx, src/modules/Toolbar/components/Filter/Filter.tsx
Added auto close on filter select, resolves ONST-157
=> feat: auto close on select

src/modules/Toolbar/components/FilterForm/FilterForm.tsx
=> fix: updated type for checkbox

src/app/search/page.tsx, src/modules/CatalogProductList/CatalogProductList.tsx, src/shared/lib/hooks.ts
add hook useDeviseSize
add CatalogProductList on Search Page
fixed offsets for scrollIntoView
fixed siblings for Pagination
ПРОБЛЕМА:
нужно сделать сброс страницы в пагинаторе на 1 при сбросе\изменении строки поиска
=> update Search Page

src/modules/CatalogProductList/CatalogProductList.tsx
=> fix: updated offset values to include filter

src/components/AddToCartBtn.tsx, src/modules/CartButton/CartButton.tsx, src/shared/redux/cart/cartSlice.ts
state isOpen, open, close move to redux
open Cart drawer after added product to cart
=> refactor CartButton, AddToCartBtn

src/app/search/page.tsx
fixed deleting name query on search page (firs render)
=> Update Search page.tsx

src/app/globals.css, src/components/AddToCartBtn.tsx, src/modules/ProductDetails/ProductDetails.tsx, src/modules/ProductDetails/ui/AdditionalInfo.tsx, src/modules/ProductDetails/ui/ProductSlider.tsx, src/modules/ProductList/ui/ProductCard.tsx, src/shared/types/types.ts
fixed styles for Product Details
fixed logic for AddToCart for unavailable product
fixed styles for ProductCard (out of stock)
=> fixed Product Details/Card

package-lock.json, package.json
Никакие же таблицы менять не надо?
=> feat: added tanstack table

src/components/ModalFooter/ModalFooter.tsx, src/components/ModalHeader/ModalHeader.tsx, src/components/Notify.tsx, src/modules/AddCategoryModal/AddCategoryModal.tsx, src/modules/CategoriesTable/CategoriesTable.tsx, src/modules/CategoriesTable/ui/CategoryRow.tsx, src/modules/DeleteCategoryModal/DeleteCategoryModal.tsx, src/modules/PaginationBar/PaginationBar.tsx, src/modules/UpdateCategoryModal/UpdateCategoryModal.tsx, src/shared/api/categoryApi.ts
I made category API to communicate with real server, but there are issues with mutations; post requests are forbidden, so I skipped them for now. And when I merged the branch (sorry about that), I've missed a mistype so it broke the deploy, I should have built the app locally to check whether it works or not, but ... So I fixed the mistake, and waiting for your approval.
=> Fixed deploy launch

src/modules/OrderTable/components/RowActions.tsx, src/modules/OrderTable/components/Table.tsx
=> Admin orders

src/shared/api/authApi.ts
=> fix: set any to updateDetails

src/components/auth/VerifyEmailForm.tsx, src/modules/AddCategoryModal/AddCategoryModal.tsx, src/shared/hooks/useAuth.ts, src/shared/lib/interceptor.ts
functionality of verify email yet not realized
=> fix: comments verify action

src/modules/Blog/Blog.tsx, src/shared/api/postApi.ts
=> fix: fixed post path

src/app/(admin)/admin/blogs/layout.tsx, src/app/(admin)/admin/blogs/page.tsx, src/app/(root)/(additional)/blog/[id]/layout.tsx, src/app/(root)/(additional)/blog/[id]/page.tsx, src/app/(root)/(additional)/blog/[id]/ui/PopularPosts.tsx, src/app/(root)/(additional)/blog/page.tsx, src/app/(root)/(additional)/blog/ui/PostList.tsx, src/app/sitemap.ts, src/components/Badge/classes.module.css, src/components/TableBody.tsx, src/components/TablePagination.tsx, src/modules/AdminBlogsDisplay/AdminBlogsDisplay.tsx, src/modules/AdminBlogsDisplay/classes.module.css, src/modules/AdminBlogsDisplay/components/Actions.tsx, src/modules/AdminBlogsDisplay/components/Header.tsx, src/modules/AdminBlogsDisplay/components/Table.tsx, src/modules/AdminBlogsDisplay/index.ts, src/modules/AdminSidebar/lib/utils.ts, src/modules/Blog/Blog.tsx, src/shared/api/postApi.ts, src/shared/lib/helpers.ts, src/shared/lib/requests.ts, src/shared/redux/store.ts
=> Added UI for blogs catalog (Admin panel)

src/modules/AdminInboxDisplay/components/Table.tsx, src/modules/OrderDetails/components/ProductTable.tsx, src/modules/OrderTable/components/Table.tsx
- Set a default sorting for some tables
- Fixed a tax and delivery display on order details' page
=> Hot fix/admin

src/components/Logout.tsx
Working on logout fix. This change can potentially fix the bug, but I need to see how it works on production
=> fix: added use callback for easier debug

src/app/(root)/(additional)/contacts/thank-you/page.tsx, src/app/(root)/profile/components/ThankYouModal.tsx, src/app/(root)/profile/components/UpdateUserForm.tsx, src/app/(root)/profile/components/UserAccount.tsx, src/app/(root)/profile/update-password/page.tsx, src/modules/Featured/Featured.tsx
- fixed button styles on home page
- removed unused button imports
=> Bugfix button

src/modules/BestSellers/BestSellers.tsx, src/modules/HeroCarousel/HeroCarousel.tsx, src/modules/ProductDetails/ui/ProductSlider.tsx
fixed mobile styles on home page
=> Bugfix / Hero Markup

src/app/(root)/profile/order-history/page.tsx, src/modules/OrdersList/components/OrderDetails.tsx, src/modules/OrdersList/components/OrderDetailsMobile.tsx, src/shared/api/ordersApi.ts
for now using https://placehold.co/600x400 as a image placeholder
=> fix: fixed order list rendering

src/shared/context/postform.context.tsx
=> fix: removed maximum length for title

src/app/(root)/(additional)/contacts/components/ContactForm.tsx, src/app/(root)/profile/components/OrderHistoryDisplay.tsx, src/modules/ProblemReport/ProblemReport.tsx, src/shared/api/contactsApi.ts, src/shared/types/feedback.types.ts
fixed 400 errors, validation and added sorting to orders
=> fix: fixed order history issues

src/modules/BestProducts/components/Table.tsx, src/modules/NewOrder/components/Option/Option.tsx, src/modules/NewOrder/components/OrderTotal/OrderTotal.tsx, src/modules/NewOrder/components/SelectedProduct/SelectedProduct.tsx, src/modules/OrderDetails/components/ProductTable.tsx
- Formatted some USD values fixing the bug: https://happytails-2023.atlassian.net/browse/ONST-373
=> Formatted USD values

src/components/Logout.tsx, src/shared/constants/localStorageKeys.ts, src/shared/lib/helpers.ts
- Emptying cart after every logout: https://happytails-2023.atlassian.net/browse/ONST-368
=> Bug fixed: there were items in cart after logout

src/modules/OrdersList/components/OrderDetails.tsx, src/modules/OrdersList/components/OrderDetailsMobile.tsx
=> Removed repeat the order button

src/app/(root)/profile/components/OrderHistoryDisplay.tsx, src/modules/OrderToolbar/OrderToolbar.tsx, src/shared/helpers/date.helpers.ts
=> Fixed filters in order history

package-lock.json, src/app/(root)/auth/callback/page.tsx, src/modules/TeamList/TeamList.tsx
I need it to test Google Login Procedure in deploy
=> For testing purposes
